### ISSUE TITLE
error: Invalid key length {"metadata":{"code":"ERR_CRYPTO_INVALID_KEYLEN","muditaCenterVersion":"2.3.1"}}

### ISSUE THREAD

**Issue by mcatanzaro** [mudita/mudita-center#2006]
# 🐛 Bug report

## 📝 Description

Mudia Center 2.3.1 is unable to connect to my Mudita Pure 1.01 phone running MuditaOS version 1.1.6.

Mudia Center says "Checking connection, please wait..." and then transitions to the "We're sorry... There was a connection problem" screen. The troubleshooting steps (disconnect device, restart device, reconnect device, unlock device) do not work.

## 👍 Expected behavior

Should connect to the phone

## 👎 Current behavior

Doesn't connect to the phone

## 🔬 Minimal Reproduction

Boot the phone. Unlock the phone. Attach it to the computer via a USB cable. Launch Mudita Center. Mudita Center automatically attempts to connect.

## 🌍 Your operating system and Mudita Center version

Fedora 40

Mudita Center 2.3.1

## 🤔 Anything else relevant?

I'm attaching a debug log with all the terminal output. I think only one line is actually relevant:

```
error: Invalid key length {"metadata":{"code":"ERR_CRYPTO_INVALID_KEYLEN","muditaCenterVersion":"2.3.1"}}
```

The error code is from OpenSSL. I have openssl-libs-1:3.2.1-2.fc40. And that's all I know; no clue what's going wrong.

The full log: [log.txt](https://github.com/user-attachments/files/16488638/log.txt)

(Bonus bug: I had to manually install `uucp` to get this far; otherwise, Mudita Center keeps trying to add me to the `dialout` and `uucp` groups again and again. Should probably ask the user to .

**Comment by dkarski** [comment]
Hi @mcatanzaro,

First of all, I apologize for the delay in responding. From what you've described, the issue is related to the Mudita Pure device. Your version is quite outdated, and we're currently focusing on developing new products. I'm not sure if this issue will ever be fixed in newer versions of Mudita Center.

However, I can suggest a workaround that might help. Try installing Mudita Center version 1.4.0, but do not update it! Then, connect your Mudita Pure and try updating your device that way. I've heard that this might help. Let me know if it works or if you encounter any other issues.

Best regards!

**Comment by mcatanzaro** [comment]
That worked. After updating MuditaOS using Mudita Center 1.4.0, I was able to use the newer Mudita Center to update to the latest MuditaOS 1.12.0.
